PX4-NuttX/nuttx branch test: px4-master_auto_rebase
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/px4-master_auto_rebase
 - https://github.com/PX4-NuttX/nuttx/commit/10cfeb30c7c349907ac0c4b365bbd6ad0f1b9a59

Changes from PX4-NuttX/nuttx (https://github.com/PX4-NuttX/nuttx/commit/d5c12b24fa5349791220ce44a46b96f345ec77c1) in current PX4/master (e2eb84042e5d15b8212b0c0ccb9045c123c39284)
https://github.com/PX4-NuttX/nuttx/compare/d5c12b24fa5349791220ce44a46b96f345ec77c1...10cfeb30c7c349907ac0c4b365bbd6ad0f1b9a59

10cfeb3 (HEAD, origin/px4-master_auto_rebase) [PX4: WIP] Fix transmission status handling in the serial interrupt
f18ab9e [PX4: REJECTED] cstdint fix
32ea740 [PX4: REJECTED] add math.h
42c5a74 [PX4: WIP] Jenkinsfile
4d64862 (origin/master) arch/arm/src/stm32fy:  IO compensation is non longer an inline function, just a plain callable function.  Not really necessary for the F7, but now the implementation is identical to the F2 and F4.
871bfac arch/arm/src/stm32:  Use of inline function for I/O compensation causes too many issues.  No just a plain callable function.
c1a2c55 arch/arm/src/stm32/stm32_gpio.h:  Correct a recently introduced compilation error:  Not all STM32s have chip/stm32_syscfg.h
f09f186 arch/arm/src/stm32f7:  Port Bob Feritich's change (2c699d781279d899cffd0446d4073a9a6ea3fa48) to STM32 F2 and F4 which appear to have identical SD support and I/O compensation requirements.
0c093f8 arch/arm/src/stm32f7:  Port Bob Feritich's change (2c699d781279d899cffd0446d4073a9a6ea3fa48) to SDMMC2 and to all other STM32F7 architectures.  Also add a conifiguration option to automatically enable I/O compensation.
2c699d7 arch/arm/src/stm32f7/chip/stm32f72xx73xx_pinmap.h: All of the SDMMC pins were set to 50 MHz, but not the clock. This sets the clock to 50 MHz also.  This combined with turning on I/O compensation makes intermittent failures go away.

Apps:
 - https://github.com/PX4-NuttX/apps/tree/px4-master_auto_rebase
 - https://github.com/PX4-NuttX/apps/commit/e14a0d8468e73f4b3eb0923e5774525072018c2b

Changes from PX4-NuttX/apps (https://github.com/PX4-NuttX/apps/commit/36806ba3d84c0fa07ed86857d4c92a997b7cd194) in current PX4/master (e2eb84042e5d15b8212b0c0ccb9045c123c39284)
https://github.com/PX4-NuttX/apps/compare/36806ba3d84c0fa07ed86857d4c92a997b7cd194...e14a0d8468e73f4b3eb0923e5774525072018c2b

e14a0d8 (HEAD -> px4-master_auto_rebase, origin/px4-master_auto_rebase) [REJECTED] add-var-expansion-in-nsh-parse.patch
2ecc94f (origin/master) apps/import/Makefile:  Eliminate a MAKE sytax error that occurs in some (but not environments) when symtab.c has not been generated.
878fa8a Squashed commit of the following:
aea8d94 apps/examples/nsh:  The symbol table name and size variale names can now be configured.
5ecec24 There many occurences of the global variable g_exports and the opportunity for collisions.  Make the global variable names unique.
e778a69 Correct more improper global variable naming:  All must begin with g_
7c1082b apps/examples/nsh:  Clean up some rather complex conditional compilation associated with the previous commit.
0ea260e apps/examples/nsh:  Add logic to automatically register an application symbol table as part of NSH initialization.
6b93881 Merged in masayuki2009/nuttx.apps/fix_helloxx (pull request #144)
654ee7e apps/examples/elf, module, posix_spawn:  Correct naming of global variables that violations the naming requirements of the coding standard.